Feature/se3cov
MobileRoboticsSkoltech/mrob pull request #82
Opened 2021-07-12 15:15 UTC by nosmokingsurfer

At the moment I make this PR to enable CI wheel building to be able to test the resulting python wheel. When all be tested, then reviewers will be added.

The following updates are made in this branch:
-  SE3cov class in cpp code;
-  comments in doxygen format in header file;
-  unit tests for SE3cov class usgin catch2 module. **to be improved**;
-  python bindings. **to be improved**;
-  python examples. **to be improved**;
-  python visualization functions;

2021-08-12 09:53 UTC, g-ferrer-sk requested changes

2021-08-12 10:10 UTC, g-ferrer-sk commented on src/geometry/examples/CMakeLists.txt
> +    TARGET_LINK_LIBRARIES(test.SE3cov SE3 Catch2::Catch2)
Yes, it needs linking, intruiguing how they do this

2021-08-12 10:19 UTC, g-ferrer-sk commented on .circleci/config.yml
> -            python3 mrobpy/tests/PC_align.py
add SE3 python

2021-08-12 10:28 UTC, g-ferrer-sk commented on src/geometry/SE3cov.cpp
> +    return compound_2nd_order((const SE3)pose, pose.cov());
you can also do SE3(pose.T()). Is this less efficient?
Maybe it is the same. we are calling constructors anyway. Let's check what is really cast doing

2021-08-12 10:30 UTC, g-ferrer-sk commented on mrobpy/examples/second_vs_fourth_compounding_order.py
> +from tqdm import tqdm
leave it here for now. Change name space for SE3_*

2021-08-12 12:08 UTC, nosmokingsurfer commented on .circleci/config.yml
> +            python3 -m pip install pytest scipy matplotlib
When I import some functions from another file, it actually executed first. It is a common thing for python:
https://stackoverflow.com/questions/6523791/why-is-python-running-my-module-when-i-import-it-and-how-do-i-stop-it

So, I believe to resolve this I should move all undesired imports under __main__ guard

2021-08-12 14:42 UTC, nosmokingsurfer commented on src/geometry/examples/CMakeLists.txt
> +    TARGET_LINK_LIBRARIES(test.SE3cov SE3 Catch2::Catch2)
single header works. because catch2 does not use target_link_libraries command now, I remove it from the root CMakeLists.txt

2021-08-12 14:46 UTC, g-ferrer-sk reviewed
looks good, is it ready for merge?

2021-08-12 14:56 UTC, nosmokingsurfer commented
@g-ferrer-sk need to resolve a couple of things first. I'm on this now. I think I will finish soon and let you know.

2021-08-12 15:28 UTC, nosmokingsurfer commented on src/geometry/SE3cov.cpp
> +    return SE3Cov(SE3::mul(pose_increment), covariance_ + adj*increment_covariance*adj.transpose());
added

2021-08-12 15:29 UTC, nosmokingsurfer commented on mrobpy/SE3py.cpp
> +        //     .def("mul",
I've returned the mul() operator to SE3cov.

2021-08-12 16:11 UTC, nosmokingsurfer commented on src/geometry/SE3cov.cpp
> +    return compound_2nd_order((const SE3)pose, pose.cov());
I did a small test with different type casts:

first run:
    Measuring the time for (const SE3):
    100000 cycles : 9343ms
    Measuring the time for static_cast:
    100000 cycles : 9361ms
    Measuring the time for SE3():
    100000 cycles : 9184ms

second run:
    Measuring the time for (const SE3):
    100000 cycles : 9487ms
    Measuring the time for static_cast:
    100000 cycles : 9379ms
    Measuring the time for SE3():
    100000 cycles : 9386ms

third run:
    Measuring the time for (const SE3):
    100000 cycles : 9415ms
    Measuring the time for static_cast:
    100000 cycles : 9281ms
    Measuring the time for SE3():
    100000 cycles : 9283ms

It looks like the static_cast and SE3() constructor are likely to be faster than (const SE3)

2021-08-12 16:17 UTC, nosmokingsurfer commented on src/geometry/SE3cov.cpp
> +    return compound_2nd_order((const SE3)pose, pose.cov());
will put SE3() everywhere

2021-08-12 16:17 UTC, nosmokingsurfer commented on src/geometry/SE3cov.cpp
> +    return compound_4th_order((const SE3)pose, pose.cov());
will put SE3()

2021-08-19 11:22 UTC, anastasiia-kornilova approved these changes

2021-08-20 09:22 UTC, g-ferrer-sk requested changes
Do we really need the .csv files? if we do, then we should move them to benchmarks, but I'm not sure this is one. If we don't, (or we don't know) then I would remove this extra overhead.

2021-08-20 11:19 UTC, nosmokingsurfer commented
@g-ferrer-sk I've removed covariance propagation example and those csv files. checks already have passed successfully

2021-08-20 15:14 UTC, g-ferrer-sk approved these changes
good

2021-08-20 15:15 UTC, merged